DROP TABLE FAKTURA CASCADE CONSTRAINTS ;

DROP TABLE KLIENT CASCADE CONSTRAINTS ;

DROP TABLE KRAJ_PRODUKCJI CASCADE CONSTRAINTS ;

DROP TABLE POZYCJA_FAKTURY CASCADE CONSTRAINTS ;

DROP TABLE PRACOWNIK CASCADE CONSTRAINTS ;

DROP TABLE SKLEP CASCADE CONSTRAINTS ;

DROP TABLE TOWAR CASCADE CONSTRAINTS ;

DROP TABLE TYP_TOWARU CASCADE CONSTRAINTS ;
