DROP VIEW najpopularniejsze_produkty;
DROP VIEW pracownik_miesiaca;
DROP VIEW dochod_30_dni;
DROP MATERIALIZED VIEW laczny_dochod;
DROP Function fn_losuj_wartosc;
DROP PROCEDURE pr_gen_transakcji_w_okresie;
DROP PROCEDURE pr_generowanie_transakcji;
DROP PROCEDURE pr_generuj_transakcje;


DROP TABLE FAKTURA ;

DROP TABLE KLIENT ;

DROP TABLE KRAJ_PRODUKCJI ;

DROP TABLE POZYCJA_FAKTURY ;

DROP TABLE PRACOWNIK ;

DROP TABLE SKLEP ;

DROP TABLE TOWAR ;

DROP TABLE TYP_TOWARU ;

DROP SEQUENCE SEQ_FAKTURAA ;

DROP SEQUENCE SEQ_KLIENTT ;

DROP SEQUENCE SEQ_PRACOWNIKK ;

DROP SEQUENCE SEQ_SKLEPP ;

DROP SEQUENCE SEQ_TOWARR ;

