DROP TABLE FAKTURA ;

DROP TABLE KLIENT ;

DROP TABLE KRAJ_PRODUKCJI ;

DROP TABLE POZYCJA_FAKTURY ;

DROP TABLE PRACOWNIK ;

DROP TABLE SKLEP ;

DROP TABLE TOWAR ;

DROP TABLE TYP_TOWARU ;

drop sequence x8_03.SEQ_FAKTURA

DROP SEQUENCE SEQ_KLIENT ;

DROP SEQUENCE SEQ_PRACOWNIK ;

DROP SEQUENCE SEQ_SKLEP ;

DROP SEQUENCE SEQ_TOWAR ;

CREATE SEQUENCE x8_03.SEQ_FAKTURA START WITH 1 INCREMENT BY 1 MINVALUE 1 ;

CREATE SEQUENCE SEQ_KLIENT START WITH 1 INCREMENT BY 1 MINVALUE 1 ;

CREATE SEQUENCE SEQ_PRACOWNIK START WITH 1 INCREMENT BY 1 MINVALUE 1 ;

CREATE SEQUENCE SEQ_SKLEP START WITH 1 INCREMENT BY 1 MINVALUE 1 ;

CREATE SEQUENCE SEQ_TOWAR START WITH 1 INCREMENT BY 1 MINVALUE 1 ;

CREATE TABLE FAKTURA
  (
    ID_FAKTURY    	INTEGER DEFAULT (x8_03.SEQ_FAKTURA.nextval) NOT NULL ,
    DATA          	DATE ,
    ID_PRACOWNIKA 	INTEGER NOT NULL ,
    ID_KLIENTA    	INTEGER NOT NULL ,
	WARTOSC_FAKTURY NUMERIC (10,2) NOT NULL
  );
ALTER TABLE FAKTURA ADD CONSTRAINT FAKTURA_PK PRIMARY KEY ( ID_FAKTURY ) ;


CREATE TABLE KLIENT
  (
    ID_KLIENTA  INTEGER DEFAULT (SEQ_KLIENT.nextval) NOT NULL ,
    IMIE        VARCHAR (20) ,
    NAZWISKO    VARCHAR (20) ,
    ULICA       VARCHAR (20) ,
    MIEJSCOWOŚĆ VARCHAR (20)
  );
ALTER TABLE KLIENT ADD CONSTRAINT KLIENT_PK PRIMARY KEY ( ID_KLIENTA ) ;


CREATE TABLE KRAJ_PRODUKCJI
  (
    ID_KRAJU    INTEGER NOT NULL ,
    NAZWA_KRAJU VARCHAR (25)
  );
ALTER TABLE KRAJ_PRODUKCJI ADD CONSTRAINT "KRAJ PRODUKCJI_PK" PRIMARY KEY ( ID_KRAJU ) ;


CREATE TABLE POZYCJA_FAKTURY
  (
    ID_POZYCJI     INTEGER NOT NULL ,
    ID_TOWARU      INTEGER NOT NULL ,
    ID_FAKTURY     INTEGER NOT NULL ,
    CENA           NUMERIC (10,2) NOT NULL ,
	ILOSC_TOWAROW  INTEGER NOT NULL  
  );
ALTER TABLE POZYCJA_FAKTURY ADD CONSTRAINT "POZYCJA FAKTURY_PK" PRIMARY KEY ( ID_POZYCJI, ID_FAKTURY ) ;


CREATE TABLE PRACOWNIK
  (
    ID_PRACOWNIKA INTEGER DEFAULT (SEQ_PRACOWNIK.nextval) NOT NULL ,
    IMIE          VARCHAR (15) ,
    NAZWISKO      VARCHAR (20) ,
    ULICA         VARCHAR (20) ,
    MIEJSCOWOŚĆ   VARCHAR (20) ,
    ID_SKLEPU     INTEGER NOT NULL
  );
ALTER TABLE PRACOWNIK ADD CONSTRAINT Pracownik_PK PRIMARY KEY ( ID_PRACOWNIKA ) ;


CREATE TABLE SKLEP
  (
    ID_SKLEPU   INTEGER DEFAULT (SEQ_SKLEP.nextval) NOT NULL ,
    Nazwa       VARCHAR (20) ,
    Ulica       VARCHAR (20) ,
    Miejscowość VARCHAR (20)
  );
ALTER TABLE SKLEP ADD CONSTRAINT SKLEP_PK PRIMARY KEY ( ID_SKLEPU ) ;


CREATE TABLE TOWAR
  (
    ID_TOWARU INTEGER DEFAULT (SEQ_TOWAR.nextval) NOT NULL ,
    CENA      NUMERIC (10,2) NOT NULL ,
    NAZWA     VARCHAR (20) NOT NULL ,
    ID_SKLEPU INTEGER NOT NULL ,
    ID_KRAJU  INTEGER NOT NULL ,
    ID_TYPU   INTEGER NOT NULL
  );
ALTER TABLE TOWAR ADD CONSTRAINT TOWAR_PK PRIMARY KEY ( ID_TOWARU ) ;


CREATE TABLE TYP_TOWARU
  (
    ID_TYPU    INTEGER NOT NULL ,
    NAZWA_TYPU VARCHAR (20)
  );
ALTER TABLE TYP_TOWARU ADD CONSTRAINT "Typ Towaru_PK" PRIMARY KEY ( ID_TYPU ) ;


ALTER TABLE FAKTURA ADD CONSTRAINT FAKTURA_KLIENT_FK FOREIGN KEY ( ID_KLIENTA ) REFERENCES KLIENT ( ID_KLIENTA );

ALTER TABLE FAKTURA ADD CONSTRAINT FAKTURA_Pracownik_FK FOREIGN KEY ( ID_PRACOWNIKA ) REFERENCES PRACOWNIK ( ID_PRACOWNIKA );

ALTER TABLE POZYCJA_FAKTURY ADD CONSTRAINT "POZYCJA FAKTURY_FAKTURA_FK" FOREIGN KEY ( ID_FAKTURY ) REFERENCES FAKTURA ( ID_FAKTURY );

ALTER TABLE POZYCJA_FAKTURY ADD CONSTRAINT "POZYCJA FAKTURY_TOWAR_FK" FOREIGN KEY ( ID_TOWARU ) REFERENCES TOWAR ( ID_TOWARU );

ALTER TABLE PRACOWNIK ADD CONSTRAINT Pracownik_SKLEP_FK FOREIGN KEY ( ID_SKLEPU ) REFERENCES SKLEP ( ID_SKLEPU );

ALTER TABLE TOWAR ADD CONSTRAINT "TOWAR_KRAJ PRODUKCJI_FK" FOREIGN KEY ( ID_KRAJU ) REFERENCES KRAJ_PRODUKCJI ( ID_KRAJU );

ALTER TABLE TOWAR ADD CONSTRAINT TOWAR_SKLEP_FK FOREIGN KEY ( ID_SKLEPU ) REFERENCES SKLEP ( ID_SKLEPU );

ALTER TABLE TOWAR ADD CONSTRAINT "TOWAR_Typ Towaru_FK" FOREIGN KEY ( ID_TYPU ) REFERENCES TYP_TOWARU ( ID_TYPU );

